// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskService.Repositories.Contexts;

namespace TaskService.Repositories.Migrations.PostgreMigrations
{
    [DbContext(typeof(TaskPostgreContext))]
    partial class TaskPostgreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TaskService.Repositories.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastSavedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSavedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TaskEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TaskInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TaskStartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TaskEntity");
                });

            modelBuilder.Entity("TaskService.Repositories.Entities.TaskSearchWordsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FindWord")
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskEntityId");

                    b.ToTable("TaskSearchWordsEntity");
                });

            modelBuilder.Entity("TaskService.Repositories.Entities.TextTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FindindWordsCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastSavedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSavedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TextId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TextTaskEntity");
                });

            modelBuilder.Entity("TaskService.Repositories.Entities.TaskSearchWordsEntity", b =>
                {
                    b.HasOne("TaskService.Repositories.Entities.TaskEntity", "TaskEntity")
                        .WithMany("TaskSearchWordsEntities")
                        .HasForeignKey("TaskEntityId");

                    b.Navigation("TaskEntity");
                });

            modelBuilder.Entity("TaskService.Repositories.Entities.TaskEntity", b =>
                {
                    b.Navigation("TaskSearchWordsEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
